services:
  flask:
    container_name: backend_sns
    build: ./backend
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    ports:
      - '5001:5000'
    depends_on:
      - db

  react:
    container_name: frontend_sns
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '5173:5173'
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    container_name: mysql_sns
    image: mysql:latest
    env_file:
      - ./backend/.env
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  mysql-data:
