[tool.ruff]
lint.select = ["E", "F", "I"]
# 保存時やコマンド実行時に自動修正を許可する
lint.fixable = ["ALL"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[[tool.mypy.overrides]]
module = "flask_login.*"
ignore_missing_imports = true
